### ISSUE TITLE
Unintentional /, * switch?

### ISSUE THREAD

**Issue by zmoon** [sethmlarson/sethmlarson.dev#16]
![Screenshot_20220123-110336.jpg](https://user-images.githubusercontent.com/15079414/150691773-7d692f67-462b-479e-b55c-ebeada440827.jpg)

**Comment by sethmlarson** [comment]
Yep! I've fixed this in https://github.com/sethmlarson/sethmlarson.dev/commit/b89268182507367dc442b50a696e6ad0a00877e9, thanks for reporting.
