### ISSUE TITLE
win percentage truncated rather than rounded?

### ISSUE THREAD

**Issue by bluefire0** [sethmlarson/sethmlarson.dev#19]
The actual imported sum percentage for my games is 97.78; however, the import tool has displayed it as 97%.  NYT website displays it as 98%. 

Stats:
1 - 0
2 - 1
3 - 29
4 - 38
5 - 16
6 - 4
losses - 2 (assuming that counts missed games)
total: 90
88/90=.9778
(screenshots forthcoming)

edit: corrected 88/90 mistake 🙄

**Comment by bluefire0** [comment]
**import tool input**
![C70CF7A1-6185-477F-A06D-BD2E649B737C](https://user-images.githubusercontent.com/5935903/162235441-28095f35-fee0-410d-91c0-9eac8ffe7db3.jpeg)

**import tool results**
![C6A4B191-CB33-41EC-BA05-C3510C9933BC](https://user-images.githubusercontent.com/5935903/162235475-9c90f11b-e04d-46ef-ab3f-f2ccaf0cc5e4.jpeg)

**nytimes.com stats from old phone**
![6142FE0F-B44C-4203-ADC5-9A889A01FF5D](https://user-images.githubusercontent.com/5935903/162235508-4cc0963f-1577-44df-9fd5-aef30b7c266a.jpeg)

**Comment by sethmlarson** [comment]
Interesting! Thanks for reporting. I believe this stat will auto-update the next time you complete the Wordle.

**Comment by bluefire0** [comment]
s/todd/did 🙃

**Comment by bluefire0** [comment]
yes, it did!

**Comment by sethmlarson** [comment]
Since this gets fixed anyways and I don't have a ton of time to devote to this project I'm going to close this issue. If you'd like to fix it yourself though you're welcome to :)

**Comment by bluefire0** [comment]
just todd today’s and yes, looks like it updated!
